Update 3-redirection new

diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -8,15 +8,28 @@ apt-get install -y nginx
 # Create the default "Hello world" page
 echo "Hello World!" > /var/www/html/index.html
 
-echo -e "\tserver_name _;
-\tlocation /redirect_me {
-\t\treturn 301 https://alxafrica.com/;
-\t}" > /tmp/new_config
+# Define the redirection configuration
+echo -e "\
+server {
+    server_name _;
+    location /redirect_me {
+        return 301 https://alxafrica.com/;
+    }
+}" > /etc/nginx/sites-available/redirect.conf
 
-sed -i '/server_name _;/{
-    r /tmp/new_config
-    d
-}' /etc/nginx/sites-available/default
+# Enable the redirection configuration by creating a symbolic link
+ln -s /etc/nginx/sites-available/redirect.conf /etc/nginx/sites-enabled/
 
-# Start the Nginx service
-service nginx restart
+# Remove the default configuration
+rm /etc/nginx/sites-enabled/default
+
+# Test the Nginx configuration
+nginx -t
+
+# If the configuration test is successful, restart Nginx
+if [ $? -eq 0 ]; then
+    service nginx restart
+    echo "Nginx restarted successfully."
+else
+    echo "Nginx configuration test failed. Please check the configuration for errors."
+fi
